config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:show, :destroy, :edit, :update]

  resources :users, only: [:show, :create, :edit, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :post_teams
  has_many :teams, through: :post_teams

  validates :winner, presence: true
  validates :seed_one, presence: true
  validates :seed_two, presence:true
  validates :seed_three, presence: true
  validates :seed_four, presence: true
  # validate :winner_must_exist_in_playoffs
  # validate :playoff_picks_must_be_unique_from_each_other
  # validates_uniqueness_of :seed_one, scope: [:seed_two, :seed_three, :seed_four]
  # validates_uniqueness_of :seed_two, scope: [:seed_one, :seed_three, :seed_four]
  # validates_uniqueness_of :seed_three, scope: [:seed_one, :seed_two, :seed_four]
  # validates_uniqueness_of :seed_four, scope: [:seed_one, :seed_two, :seed_three]
  def winner_must_exist_in_playoffs
    if (:winner != :seed_one || :winner != :seed_two || :winner != :seed_three || :winner != :seed_four)
      errors.add(:winner, "must also be included as one of your playoff picks.")
    end
  end

  def playoff_picks_must_be_unique_from_each_other
    if (:seed_one == :seed_two || :seed_one == :seed_three || :seed_one == :seed_four || :seed_two == :seed_three || :seed_two == :seed_four || :seed_three == :seed_four)
      errors.add("Your playoff picks must be different from each other.")
    end      
  end
end

app/models/post_team.rb
class PostTeam < ActiveRecord::Base
  belongs_to :team
  belongs_to :post
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :post_teams
  has_many :posts, through: :post_teams
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  has_secure_password validations: false
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 6}  
  validates :location, presence: true
  validates :favorite_team, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end


  def require_user
    if !logged_in?
      flash["error"] = "Must be logged in to do that."
      redirect_to root_path
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user, except: [:show, :index]
  before_action :require_first_time, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    # binding.pry
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash["notice"] = "Your submission was created."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:winner, :seed_one, :seed_two, :seed_three, :seed_four) #team_ids: [])
  end

  def require_first_time
    if current_user.posts.first
      flash["error"] = "You can only make one submission"
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_user, only: [:destroy]

  def new
    
  end

  def create
    user = User.where(username: params[:username]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash["notice"] = "Welcome, you've logged in."
      redirect_to root_path
    else
      flash["error"] = "There is something wrong with your username or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash["notice"] = "You've logged out."
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def show
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash["notice"] = "You are registered."
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash["notice"] = "Your profile was updated."
      redirect_to user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :location, :favorite_team)
  end

  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user
      flash["error"] = "You are not allowed to do that."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "CFP Predictions!", root_path, :class => 'brand' %>
  </li>
<!--<li>
    <%= link_to 'Player Picks', '' %>
  </li>-->
</ul>
<% if logged_in? %>
  <% if !current_user.posts.first %>
    <div class='nav_item'>
      <%= link_to "New Submission", new_post_path, class: 'btn btn-default btn-small' %>
    </div>
  <% end %>
</hbr>
  <div class='nav-item  btn-group'>
    <%= link_to('', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown') do %>
      <%= current_user.username %>
      <span class='caret'></span>
    <% end %>
    <ul class='dropdown-menu'>
      <li>
        <%= link_to edit_user_path(current_user) do %>
        <i class='icon-pencil'></i>
        edit profile
        <% end %>
      </li>
      <li>
        <%= link_to user_path(current_user) do %>
        <i class='icon-user'></i>
        view profile/submission
        <% end %>
      </li>
      <li>
        <%= link_to logout_path do %>
        <i class='icon-circle-arrow-left'></i>
        logout
        <% end %>
      </li>
    </ul>
  </div>
<% else %>
  <div class='nav_item'>
    <%= link_to "Register", register_path, class: 'btn btn-success btn-small' %>
  </div>
  <div class='nav_item'>
    <%= link_to "Login", login_path, class: 'btn btn-primary btn-small' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CFP Predictions</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar navbar-inverse navbar-static-top">
        <div class="navbar-inner">
          <div class="container" id="main">
            <%= render 'layouts/navigation' %>

          </div>

        </div>

      </div>
    </header>
    <%= yield %>
    <!-- <div id="main" role="main"> -->
      
      <!-- <footer> -->
      <!-- </footer> --> <!--! end of .container -->
     <!-- </div> --><!--! end of #main -->
  </body>
</html>

app/views/posts/index.html.erb
<%= image_tag('CFP_logo.jpg') %>
<div class="container">
  <div class="row">
    <div class="span12">
    </br>
      <%= render 'layouts/messages' %>
    </div>
  </div>
</div>
</br>
<div class='container-fluid'>
  <h1 class='text-center'>Player Picks</h1>
  <hr/>
    <% @posts.each_slice(3) do |slice_of_posts| %>
      <div class='row-fluid'>
        <% slice_of_posts.each do |post| %>
      <div class='span4 well'>
        <h3 class='text-center'><%= link_to post.creator.username, user_path(post.creator) %>'s Submission:</h3>
        <dl class='dl-horizontal'>
          <dt>Championship Winner:</dt>
            <dd><%= post.winner %></dd>
          </br>
          <dt>Playoff Picks:</dt>
            <dd>
              <ol>
                  <li> <%= post.seed_one %> </li>
                  <li> <%= post.seed_two %> </li>
                  <li> <%= post.seed_three %> </li>
                  <li> <%= post.seed_four %> </li>
              </ol>
            </dd>
        </dl>
      </div>
      <% end %>
      </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<div class='container'>
</br>
<% if @post.errors.any? %>
<div class='row'>
  <div class='alert alert-error span8' >
  <h5>Please fix the following errors: </h5>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  </div>
<% end %>
  <div class='well span12'> 
    <%= form_for @post do |f| %>
      <h4>2015 College Football Champion:</h4>
      <%= f.select(:winner, Team.order(:name).all.map { |u| [u.name, u.name] }, prompt: "Pick Winning Team") %>
      <div class='control-group'>
        <p><strong>Four Teams to make Playoffs <small>(seeded 1 - 4 from left to right)</small>:</strong></p>
        <%= f.select(:seed_one, Team.order(:name).all.map { |u| [u.name, u.name] }, prompt: "Pick 1st seed") %>
        <%= f.select(:seed_two, Team.order(:name).all.map { |u| [u.name, u.name] }, prompt: "Pick 2nd seed") %>
        <%= f.select(:seed_three, Team.order(:name).all.map { |u| [u.name, u.name] }, prompt: "Pick 3rd seed") %>
        <%= f.select(:seed_four, Team.order(:name).all.map { |u| [u.name, u.name] }, prompt: "Pick 4th seed") %>
        <!--<%= f.collection_check_boxes :team_ids, Team.order(:name),:id,:name do |cb| %>
          <% cb.label(class: "checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
        <% end %>-->
      </div>
      <div class='control-group'>
        <%= f.submit "Submit", class: 'btn btn-primary' %>
      </div>
    <% end %>
    <h3 class='text-center'>Available Teams to Choose</h3>
    <div class='row-fluid'>
      <div class='well span4' id='new'>
        <h4 class='text-center'><strong>ACC</strong></h4>
        <ul>
          <% Team.where(conference: "ACC").each do |team| %>
              <li><%= team.name %></li>
          <% end %>
        </ul>
      </div>
      <div class='well span4' id='new'>
        <h4 class='text-center'><strong>BIG 10</strong></h4>
        <ul>
          <% Team.where(conference: "Big 10").each do |team| %>
              <li><%= team.name %></li>
          <% end %>
        </ul>
      </div>
      <div class='well span4' id='new'>
        <h4 class='text-center'><strong>BIG 12</strong></h4>
        <ul>
          <% Team.where(conference: "Big 12").each do |team| %>
              <li><%= team.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class='row-fluid' >
      <div class='well span4' id='new'>
        <h4 class='text-center'><strong>PAC 12</strong></h4>
        <ul>
          <% Team.where(conference: "Pac-12").each do |team| %>
              <li><%= team.name %></li>
          <% end %>
        </ul>
      </div>
      <div class='well span4' id='new'>
        <h4 class='text-center'><strong>SEC</strong></h4>
        <ul>
          <% Team.where(conference: "SEC").each do |team| %>
              <li><%= team.name %></li>
          <% end %>
        </ul>
      </div>
      <div class='well span4' id='new'>
        <h4 class='text-center'><strong>FBS Independents</strong></h4>
        <ul>
          <% Team.where(conference: "FBS Independents").each do |team| %>
              <li><%= team.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container'<div class='container'>
</br>
  <% if @user.errors.any? %>
  <div class='row'>
    <div class='alert alert-error span8' >
    <h5>Please fix the following errors: </h5>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      </div>
    </div>
  <% end %>
  <div class='well'>
    <%= form_for @user do |f| %>
    <div class='control-group'>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class='control-group'>
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>
    <div class='control-group'>
      <%= f.label 'Favorite Team' %>
      <%= f.text_field :favorite_team %>
    </div>
    <%= f.submit 'Update', class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class='container'>
</br>
  <% if @user.errors.any? %>
  <div class='row'>
    <div class='alert alert-error span8' >
    <h5>Please fix the following errors: </h5>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      </div>
    </div>
  <% end %>
  <div class='well'>
    <%= form_for @user do |f| %>
    <div class='control-group'>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class='control-group'>
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>
    <div class='control-group'>
      <%= f.label 'Favorite Team' %>
      <%= f.text_field :favorite_team %>
    </div>
    <%= f.submit 'Register', class: 'btn btn-success' %>
    <% end %>
  </div>
</div>
    

app/views/users/show.html.erb
</br>
<div class='container'>
  <div class='well'>
    <dl class='dl-horizontal'>
      <dt>Username:</dt>
      <dd><%= @user.username %></dd>
    </dl>
    <dl class='dl-horizontal'>
      <dt>Location:</dt>
      <dd><%= @user.location %></dd>
    </dl>
    <dl class='dl-horizontal'>
      <dt>Favorite Team:</dt>
      <dd><%= @user.favorite_team %></dd>
    </dl>
  </div>
  <% if @user.posts.first %>
    <h5><%= @user.username %>'s Submission</h5>

    <div class='well'>
      <dl class='dl-horizontal'>
          <dt>Championship Winner:</dt>
            <dd><%= @user.posts.first.winner %></dd>
          </br>
          <dt>Playoff Picks:</dt>
            <dd>
              <ol>
                  <li> <%= @user.posts.first.seed_one %> </li>
                  <li> <%= @user.posts.first.seed_two %> </li>
                  <li> <%= @user.posts.first.seed_three %> </li>
                  <li> <%= @user.posts.first.seed_four %> </li>
              </ol>
            </dd>
        </dl>
    </div>
  <% end %>
</div>